name = "flyx-v3"

main = ".open-next/worker.js"

compatibility_date = "2026-09-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "flyx-v3-db"
database_id = "6804a539-6300-425c-acad-4aa027c79122"

[[kv_namespaces]]
binding = "CACHE"
id = "flyx-cache"

[vars]
FLYX_DEPLOY_TARGET = "cloudflare"
FLYX_NO_BROWSER = "true"

[observability]
enabled = false
